### ISSUE TITLE
Re-organise modules

### ISSUE THREAD

**Issue by smassonnet** [LSIR/mlmodule#124]
New proposed organisation:

`mlmodule`: Root module
- [x] `callbacks` (#141): Base classes to define callbacks with implementation for common use-cases (in-memory...)
- [x] `cli`: Command-line interface implementation
- [x] `helpers` (#147): Re-usable helper functions
- [x] `labels`: Classes to define set of labels
- [x] `models` (#140, #142): Models implementations (previously called `contrib`). Should also define `ModelWithState` and `ModelWithLabels`.
- [x] `predictions` (#144): Classes to define data produced by a model. Also contains predictions serialization.
- [x] `runners` (#143): Base classes to define a runner
- [x] `states` (#145): Classes to define model state management
- [x] `stores` (#145): Classes to define model state's stores.
- [x] `testing` (#147):: Utility classes for testing purposes
- [x] `torch` (#146): Torch implementation of models and runners.
